# packages in environment at C:\Users\David\Miniconda3\envs\mlearn:
#
# Name                    Version                   Build  Channel
ca-certificates           2017.08.26           h94faf87_0  
intel-openmp              2018.0.0             hd92c6cd_8  
python-dateutil           2.6.1            py36h509ddcb_1  
scikit-learn              0.19.1           py36h53aea1b_0  
